import {NextRequest} from 'next/server';import {PremiumError,premiumAdmin,premiumFailure,premiumResponse} from '@/lib/premium/server';
export const runtime='nodejs';export const maxDuration=60;
export async function POST(request:NextRequest){try{const {supabase,user}=await premiumAdmin(request);const body=await request.json().catch(()=>({}));if(body.confirmation!=='ATIVAR PLANOS E TRANSICAO')throw new PremiumError('Confirmação de ativação inválida.',400);
  const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY||process.env.SUPABASE_SECRET_KEY;
  if(!process.env.MERCADOPAGO_ACCESS_TOKEN||!serviceKey)throw new PremiumError('Credenciais privadas de pagamento e Supabase precisam estar configuradas.',503);
  const current=await supabase.from('premium_settings').select('*').single();if(current.error)throw current.error;if(current.data.enforcement_enabled)return premiumResponse({alreadyActive:true});
  const cutoff=current.data.transition_starts_at||new Date().toISOString();if(!current.data.transition_starts_at){const start=await supabase.from('premium_settings').update({transition_starts_at:cutoff}).eq('id',true);if(start.error)throw start.error;}
  let eligible=0,granted=0;const errors:string[]=[];for(let page=1;;page++){const listed=await supabase.auth.admin.listUsers({page,perPage:1000});if(listed.error)throw listed.error;for(const account of listed.data.users){if(!account.email_confirmed_at||account.created_at>cutoff)continue;eligible++;const grant=await supabase.rpc('premium_grant_access',{p_user_id:account.id,p_plan_id:current.data.transition_plan_id,p_duration_days:current.data.transition_duration_days,p_source_type:'PROMOTION',p_source_id:'existing-users-transition-2026',p_idempotency_key:`transition:${account.id}`,p_actor_id:user.id,p_reason:'Transição dos usuários existentes na ativação comercial',p_partner_id:null});if(grant.error)errors.push(account.id);else granted++;}if(listed.data.users.length<1000)break;}
  if(errors.length)throw new PremiumError(`Ativação interrompida: ${errors.length} concessões precisam ser revisadas.`,409);
  const activated=await supabase.from('premium_settings').update({commercial_enabled:true,enforcement_enabled:true,purchase_reward_enabled:true}).eq('id',true);if(activated.error)throw activated.error;await supabase.from('premium_audit').insert({actor_id:user.id,action:'COMMERCIAL_ACTIVATION',entity:'premium_settings',entity_id:'true',after_state:{cutoff,eligible,granted},origin:'admin_api'});return premiumResponse({activated:true,cutoff,eligible,granted});
}catch(error){return premiumFailure(error);}}
