'use client';
import Link from 'next/link';import {ChangeEvent,useEffect,useState} from 'react';import readXlsxFileRaw from 'read-excel-file/browser';import {supabase} from '@/supabase';
const readXlsxFile=readXlsxFileRaw as unknown as (file:File)=>Promise<any[][]>;
type Row={name:string;email:string};
function parseCsv(text:string):Row[]{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const sep=lines[0].includes(';')?';':',';const head=lines[0].split(sep).map(v=>v.trim().toLowerCase());const ni=head.findIndex(v=>['nome','name'].includes(v)),ei=head.findIndex(v=>['email','e-mail'].includes(v));if(ei<0)throw new Error('A coluna email é obrigatória.');return lines.slice(1).map(line=>{const v=line.split(sep).map(x=>x.trim().replace(/^"|"$/g,''));return{name:ni>=0?v[ni]||'':'',email:v[ei]||''};});}
export default function Importar(){const [partners,setPartners]=useState<any[]>([]),[partnerId,setPartnerId]=useState(''),[reference,setReference]=useState(''),[rows,setRows]=useState<Row[]>([]),[preview,setPreview]=useState<any>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function token(){const {data}=await supabase.auth.getSession();if(!data.session)throw new Error('Entre como administrador.');return data.session.access_token;}
  useEffect(()=>{token().then(t=>fetch('/api/admin/premium',{headers:{Authorization:`Bearer ${t}`}})).then(r=>r.json()).then(d=>{setPartners(d.partners||[]);setPartnerId(d.partners?.find((p:any)=>p.active)?.id||'');}).catch(e=>setError(e.message));},[]);
  async function fileChanged(e:ChangeEvent<HTMLInputElement>){try{setError('');setPreview(null);const file=e.target.files?.[0];if(!file)return;let parsed:Row[]=[];if(file.name.toLowerCase().endsWith('.xlsx')){const sheet=await readXlsxFile(file);const headers=sheet[0].map(v=>String(v||'').trim().toLowerCase());const ni=headers.findIndex(v=>['nome','name'].includes(v)),ei=headers.findIndex(v=>['email','e-mail'].includes(v));if(ei<0)throw new Error('A coluna email é obrigatória.');parsed=sheet.slice(1).map(r=>({name:ni>=0?String(r[ni]||''):'',email:String(r[ei]||'')}));}else parsed=parseCsv(await file.text());if(!parsed.length)throw new Error('O arquivo não possui beneficiários.');if(parsed.length>2000)throw new Error('O limite por lote é 2.000 linhas.');setRows(parsed);}catch(e){setRows([]);setError(e instanceof Error?e.message:'Falha ao ler arquivo.');}}
  async function send(action:'preview'|'confirm'){try{setBusy(true);setError('');setMessage('');const response=await fetch('/api/admin/premium/imports',{method:'POST',headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json'},body:JSON.stringify({action,partnerId,reference,rows})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(action==='preview')setPreview(data);else{setMessage(`Lote confirmado: ${data.counts.activated} ativados e ${data.counts.pending} pendentes.`);setPreview(null);setRows([]);}}catch(e){setError(e instanceof Error?e.message:'Falha na importação.');}finally{setBusy(false);}}
  return <main className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-4xl"><Link href="/admin/premium" className="font-bold text-viva-roxo">← Planos & Benefícios</Link><h1 className="mt-4 text-3xl font-black">Importar beneficiários</h1><p className="mt-2 text-slate-600">CSV ou XLSX com colunas nome e email. Nada é concedido antes da confirmação.</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{message&&<p role="status" className="mt-4 rounded-xl bg-green-50 p-4 text-green-800">{message}</p>}
    <section className="mt-6 grid gap-4 rounded-2xl border bg-white p-6"><label>Parceiro<select className="w-full rounded-xl border p-3" value={partnerId} onChange={e=>setPartnerId(e.target.value)}>{partners.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Referência única do lote<input className="w-full rounded-xl border p-3" placeholder="STRONGFIT-2026-09" value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Arquivo<input className="block w-full rounded-xl border p-3" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={fileChanged}/></label><button disabled={busy||!partnerId||!reference||!rows.length} onClick={()=>send('preview')} className="rounded-xl bg-viva-roxo p-3 font-bold text-white disabled:bg-slate-300">Analisar {rows.length||''} registros</button></section>
    {preview&&<section className="mt-6 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Prévia — {preview.partner.name}</h2><p>{preview.partner.plan} · {preview.partner.durationDays} dias</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(preview.counts).map(([k,v])=><div key={k} className="rounded-lg bg-slate-100 p-3"><strong className="block text-xl">{String(v)}</strong>{k}</div>)}</div><button disabled={busy} onClick={()=>send('confirm')} className="mt-5 rounded-xl bg-green-700 px-5 py-3 font-bold text-white">Confirmar importação</button></section>}</div></main>}
