import {NextRequest} from 'next/server';
import {z} from 'zod';
import {PremiumError,premiumAdmin,premiumFailure,premiumResponse} from '@/lib/premium/server';
import {processPremiumEmailOutbox} from '@/lib/premium/email';
const rowSchema=z.object({name:z.string().trim().max(200).default(''),email:z.string().trim().max(320)}).strict();
const schema=z.object({action:z.enum(['preview','confirm']),partnerId:z.string().uuid(),reference:z.string().trim().min(1).max(120),rows:z.array(rowSchema).min(1).max(2000)}).strict();
const emailOk=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)&&value.length<=254;
async function authMap(supabase:any,emails:Set<string>){const map=new Map<string,string>();for(let page=1;;page++){const {data,error}=await supabase.auth.admin.listUsers({page,perPage:1000});if(error)throw error;for(const user of data.users){const email=user.email?.trim().toLowerCase();if(email&&emails.has(email)&&user.email_confirmed_at)map.set(email,user.id);}if(data.users.length<1000)break;}return map;}
export async function POST(request:NextRequest){try{const {supabase,user}=await premiumAdmin(request);const raw=await request.text();if(raw.length>1000000)throw new PremiumError('Arquivo excede o limite.',413);
  let body;try{body=schema.parse(JSON.parse(raw));}catch{throw new PremiumError('Arquivo, parceiro ou referência inválidos.',400);}
  const partnerResult=await supabase.from('premium_partners').select('*,premium_plans(*)').eq('id',body.partnerId).eq('active',true).maybeSingle();if(partnerResult.error)throw partnerResult.error;if(!partnerResult.data)throw new PremiumError('Parceiro indisponível.',404);const partner=partnerResult.data;
  const seen=new Set<string>();const rows=body.rows.map((row,index)=>{const email=row.email.toLowerCase();let status='VALID';if(!emailOk(email))status='INVALID';else if(seen.has(email))status='DUPLICATE';else seen.add(email);return{rowNumber:index+2,name:row.name,email,normalizedEmail:email,status};});
  const users=await authMap(supabase,seen);const active=users.size?await supabase.from('premium_grants').select('user_id,plan_id,expires_at,status').in('user_id',Array.from(users.values())).eq('plan_id',partner.plan_id).in('status',['ACTIVE','REVIEW_REQUIRED']).gt('expires_at',new Date().toISOString()):{data:[],error:null};if(active.error)throw active.error;const activeUsers=new Set((active.data||[]).map((x:any)=>x.user_id));
  for(const row of rows)if(row.status==='VALID'){const uid=users.get(row.normalizedEmail);row.status=uid?(activeUsers.has(uid)?'ALREADY_ACTIVE':'EXISTING_USER'):'PENDING_USER';}
  const counts={total:rows.length,valid:rows.filter(r=>!['INVALID','DUPLICATE'].includes(r.status)).length,invalid:rows.filter(r=>r.status==='INVALID').length,duplicates:rows.filter(r=>r.status==='DUPLICATE').length,existing:rows.filter(r=>r.status==='EXISTING_USER').length,pending:rows.filter(r=>r.status==='PENDING_USER').length,alreadyActive:rows.filter(r=>r.status==='ALREADY_ACTIVE').length,newBenefits:rows.filter(r=>['EXISTING_USER','PENDING_USER','ALREADY_ACTIVE'].includes(r.status)).length};
  if(body.action==='preview')return premiumResponse({partner:{id:partner.id,name:partner.name,plan:partner.premium_plans.name,durationDays:partner.duration_days},counts,rows});
  const duplicate=await supabase.from('premium_import_batches').select('id').eq('partner_id',partner.id).eq('reference',body.reference).maybeSingle();if(duplicate.error)throw duplicate.error;if(duplicate.data)throw new PremiumError('Já existe um lote com esta referência para o parceiro.',409);
  const batchResult=await supabase.from('premium_import_batches').insert({partner_id:partner.id,reference:body.reference,created_by:user.id,plan_id:partner.plan_id,duration_days:partner.duration_days,total_rows:counts.total,valid_rows:counts.valid,invalid_rows:counts.invalid,duplicated_rows:counts.duplicates,status:'PREVIEW'}).select().single();if(batchResult.error)throw batchResult.error;const batch=batchResult.data;let activated=0,pending=0,failed=0;
  for(const row of rows){const uid=users.get(row.normalizedEmail);const inserted=await supabase.from('premium_import_rows').insert({batch_id:batch.id,row_number:row.rowNumber,name:row.name,email:row.email,normalized_email:row.normalizedEmail,status:row.status}).select().single();if(inserted.error){failed++;continue;}if(['EXISTING_USER','ALREADY_ACTIVE'].includes(row.status)&&uid){const source=partner.partner_type==='CANAL PRÓPRIO'?'VIP_GROUP':'PARTNER';const grant=await supabase.rpc('premium_grant_access',{p_user_id:uid,p_plan_id:partner.plan_id,p_duration_days:partner.duration_days,p_source_type:source,p_source_id:partner.id,p_idempotency_key:`import:${batch.id}:${row.normalizedEmail}`,p_actor_id:user.id,p_reason:`Lote ${body.reference}`,p_partner_id:partner.id});if(grant.error){failed++;await supabase.from('premium_import_rows').update({status:'ERROR',error_message:'Falha ao conceder benefício.'}).eq('id',inserted.data.id);}else{activated++;await supabase.from('premium_import_rows').update({status:'ACTIVATED',user_id:uid,grant_id:grant.data}).eq('id',inserted.data.id);}}
    else if(row.status==='PENDING_USER'){const pb=await supabase.from('premium_pending_benefits').insert({email:row.email,normalized_email:row.normalizedEmail,name:row.name,partner_id:partner.id,plan_id:partner.plan_id,duration_days:partner.duration_days,import_batch_id:batch.id,import_row_id:inserted.data.id}).select().single();if(pb.error){failed++;continue;}pending++;await supabase.from('premium_import_rows').update({status:'PENDING_REGISTRATION'}).eq('id',inserted.data.id);await supabase.from('premium_email_outbox').insert({template_code:'PARTNER_INVITE',recipient_email:row.email,partner_id:partner.id,pending_benefit_id:pb.data.id,variables:{name:row.name,partner_name:partner.name,plan_name:partner.premium_plans.name,duration_days:partner.duration_days,activation_url:'https://www.vivalevedf.com.br/login?next=/meu-plano'}});}}
  const status=failed?'PARTIAL':'CONFIRMED';await supabase.from('premium_import_batches').update({activated_rows:activated,pending_rows:pending,status,confirmed_at:new Date().toISOString()}).eq('id',batch.id);await supabase.from('premium_audit').insert({actor_id:user.id,action:'CONFIRM_IMPORT',entity:'premium_import_batches',entity_id:batch.id,after_state:{counts,activated,pending,failed},origin:'admin_api'});const email=await processPremiumEmailOutbox(Math.min(pending,25));return premiumResponse({batchId:batch.id,status,email,counts:{...counts,activated,pending,failed}});
}catch(error){return premiumFailure(error);}}
