-- Reserve the flavours of paid kits without blocking stock for pending checkouts.
alter table public.produtos
  add column if not exists estoque_reservado integer not null default 0;

alter table public.produtos
  add column if not exists estoque_disponivel integer
  generated always as (estoque - estoque_reservado) stored;

alter table public.produtos drop constraint if exists produtos_estoque_reservado_check;
alter table public.produtos
  add constraint produtos_estoque_reservado_check
  check (estoque_reservado >= 0 and estoque_reservado <= estoque);

create table if not exists public.estoque_reservas_kit (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id),
  pedido_entrega_id bigint not null references public.pedidos(id),
  produto_id bigint not null references public.produtos(id),
  quantidade integer not null check (quantidade > 0),
  status text not null default 'reservado'
    check (status in ('reservado', 'consumido', 'liberado')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create unique index if not exists estoque_reservas_kit_entrega_produto_reservado_uidx
  on public.estoque_reservas_kit (pedido_entrega_id, produto_id)
  where status = 'reservado';
create index if not exists estoque_reservas_kit_pedido_status_idx
  on public.estoque_reservas_kit (pedido_id, status);
create index if not exists estoque_reservas_kit_produto_status_idx
  on public.estoque_reservas_kit (produto_id, status);

alter table public.estoque_reservas_kit enable row level security;
drop policy if exists estoque_reservas_kit_bloquear_acesso_direto on public.estoque_reservas_kit;
create policy estoque_reservas_kit_bloquear_acesso_direto
  on public.estoque_reservas_kit
  as restrictive for all to public
  using (false) with check (false);
revoke all on public.estoque_reservas_kit from public, anon, authenticated;
grant all on public.estoque_reservas_kit to service_role;
revoke all on sequence public.estoque_reservas_kit_id_seq from public, anon, authenticated;
grant usage, select on sequence public.estoque_reservas_kit_id_seq to service_role;

create or replace function public.validar_limites_estoque_produto()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if new.estoque is null or new.estoque < 0 then
    raise exception 'O estoque físico não pode ser negativo.';
  end if;
  if new.estoque_reservado is null or new.estoque_reservado < 0 then
    raise exception 'O estoque reservado não pode ser negativo.';
  end if;
  if new.estoque_reservado > new.estoque then
    raise exception 'O estoque físico não pode ficar abaixo das % unidade(s) reservadas.', new.estoque_reservado;
  end if;
  return new;
end;
$$;

drop trigger if exists validar_limites_estoque_produto_trigger on public.produtos;
create trigger validar_limites_estoque_produto_trigger
before insert or update of estoque, estoque_reservado on public.produtos
for each row execute function public.validar_limites_estoque_produto();

create or replace function public.reservar_estoque_kit_pedido(p_pedido_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_produto record;
begin
  perform 1
    from public.pedidos
   where id = p_pedido_id
     and plano_id is null
   for update;
  if not found then
    raise exception 'Pedido principal % não encontrado.', p_pedido_id;
  end if;

  for v_produto in
    with demanda as (
      select (item->>'id')::bigint as produto_id,
             sum((item->>'quantidade')::integer)::integer as quantidade
        from public.pedidos entrega
        cross join lateral jsonb_array_elements(entrega.itens) item
       where entrega.pedido_origem_id = p_pedido_id
         and entrega.plano_id is not null
         and entrega.status <> 'Cancelado'
         and not entrega.plano_estoque_baixado
         and not exists (
           select 1 from public.estoque_reservas_kit reserva
            where reserva.pedido_entrega_id = entrega.id
              and reserva.produto_id = (item->>'id')::bigint
              and reserva.status = 'reservado'
         )
       group by 1
    )
    select demanda.produto_id, demanda.quantidade
      from demanda
     order by demanda.produto_id
  loop
    update public.produtos
       set estoque_reservado = estoque_reservado + v_produto.quantidade
     where id = v_produto.produto_id
       and estoque - estoque_reservado >= v_produto.quantidade;
    if not found then
      raise exception 'Estoque disponível insuficiente para reservar o produto % do kit.', v_produto.produto_id;
    end if;
  end loop;

  insert into public.estoque_reservas_kit
    (pedido_id, pedido_entrega_id, produto_id, quantidade)
  select p_pedido_id,
         entrega.id,
         (item->>'id')::bigint,
         sum((item->>'quantidade')::integer)::integer
    from public.pedidos entrega
    cross join lateral jsonb_array_elements(entrega.itens) item
   where entrega.pedido_origem_id = p_pedido_id
     and entrega.plano_id is not null
     and entrega.status <> 'Cancelado'
     and not entrega.plano_estoque_baixado
     and not exists (
       select 1 from public.estoque_reservas_kit reserva
        where reserva.pedido_entrega_id = entrega.id
          and reserva.produto_id = (item->>'id')::bigint
          and reserva.status = 'reservado'
     )
   group by entrega.id, (item->>'id')::bigint
   order by entrega.id, (item->>'id')::bigint;
end;
$$;

create or replace function public.liberar_reserva_estoque_kit_entrega(p_pedido_entrega_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_produto record;
begin
  for v_produto in
    select produto_id, sum(quantidade)::integer as quantidade
      from public.estoque_reservas_kit
     where pedido_entrega_id = p_pedido_entrega_id
       and status = 'reservado'
     group by produto_id
     order by produto_id
  loop
    update public.produtos
       set estoque_reservado = estoque_reservado - v_produto.quantidade
     where id = v_produto.produto_id
       and estoque_reservado >= v_produto.quantidade;
    if not found then
      raise exception 'Inconsistência ao liberar a reserva do produto %.', v_produto.produto_id;
    end if;
  end loop;

  update public.estoque_reservas_kit
     set status = 'liberado', atualizado_em = now()
   where pedido_entrega_id = p_pedido_entrega_id
     and status = 'reservado';
end;
$$;

create or replace function public.liberar_reservas_estoque_kit_pedido(p_pedido_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_entrega record;
begin
  for v_entrega in
    select distinct pedido_entrega_id
      from public.estoque_reservas_kit
     where pedido_id = p_pedido_id
       and status = 'reservado'
     order by pedido_entrega_id
  loop
    perform public.liberar_reserva_estoque_kit_entrega(v_entrega.pedido_entrega_id);
  end loop;
end;
$$;

create or replace function public.gerenciar_reserva_pagamento_kit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.plano_id is null
     and new.pagamento_status = 'approved'
     and new.pagamento_status is distinct from old.pagamento_status then
    perform public.reservar_estoque_kit_pedido(new.id);
  elsif new.plano_id is null
     and old.pagamento_status = 'approved'
     and new.pagamento_status in ('refunded', 'charged_back', 'cancelled')
     and new.pagamento_status is distinct from old.pagamento_status then
    perform public.liberar_reservas_estoque_kit_pedido(new.id);
  end if;

  if new.plano_id is null
     and new.status = 'Cancelado'
     and new.status is distinct from old.status then
    perform public.liberar_reservas_estoque_kit_pedido(new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists ac_gerenciar_reserva_pagamento_kit on public.pedidos;
create trigger ac_gerenciar_reserva_pagamento_kit
before update of pagamento_status, status on public.pedidos
for each row execute function public.gerenciar_reserva_pagamento_kit();

create or replace function public.baixar_estoque_entrega_plano()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_item record;
  v_reservado integer;
begin
  if new.plano_id is not null
     and new.status = 'Cancelado'
     and new.status is distinct from old.status
     and not old.plano_estoque_baixado then
    perform public.liberar_reserva_estoque_kit_entrega(new.id);
  end if;

  if new.plano_id is not null
     and not old.plano_estoque_baixado
     and new.status in ('Em Preparo', 'Pronta', 'Saiu para Entrega') then
    for v_item in
      select (item->>'id')::bigint as produto_id,
             sum((item->>'quantidade')::integer)::integer as quantidade
        from jsonb_array_elements(new.itens) item
       group by 1
       order by 1
    loop
      select coalesce(sum(quantidade), 0)::integer
        into v_reservado
        from public.estoque_reservas_kit
       where pedido_entrega_id = new.id
         and produto_id = v_item.produto_id
         and status = 'reservado';

      if v_reservado > 0 then
        if v_reservado <> v_item.quantidade then
          raise exception 'A reserva do produto % não corresponde à entrega.', v_item.produto_id;
        end if;
        update public.produtos
           set estoque = estoque - v_item.quantidade,
               estoque_reservado = estoque_reservado - v_item.quantidade
         where id = v_item.produto_id
           and estoque >= v_item.quantidade
           and estoque_reservado >= v_item.quantidade;
        if not found then
          raise exception 'Estoque reservado inconsistente para preparar o produto %.', v_item.produto_id;
        end if;
        update public.estoque_reservas_kit
           set status = 'consumido', atualizado_em = now()
         where pedido_entrega_id = new.id
           and produto_id = v_item.produto_id
           and status = 'reservado';
      else
        -- Compatibility path for deliveries prepared before payment/reservation.
        update public.produtos
           set estoque = estoque - v_item.quantidade
         where id = v_item.produto_id
           and estoque - estoque_reservado >= v_item.quantidade;
        if not found then
          raise exception 'Estoque disponível insuficiente para preparar o produto %.', v_item.produto_id;
        end if;
      end if;
    end loop;
    new.plano_estoque_baixado := true;
  end if;
  return new;
end;
$$;

revoke all on function public.validar_limites_estoque_produto(),
  public.reservar_estoque_kit_pedido(bigint),
  public.liberar_reserva_estoque_kit_entrega(bigint),
  public.liberar_reservas_estoque_kit_pedido(bigint),
  public.gerenciar_reserva_pagamento_kit(),
  public.baixar_estoque_entrega_plano()
from public, anon, authenticated;
grant execute on function public.reservar_estoque_kit_pedido(bigint) to service_role;

comment on column public.produtos.estoque_reservado is
  'Quantidade comprometida por kits pagos e ainda não preparada.';
comment on column public.produtos.estoque_disponivel is
  'Estoque físico menos as unidades reservadas por kits pagos.';
comment on table public.estoque_reservas_kit is
  'Histórico idempotente das reservas, consumos e liberações de estoque por entrega de kit.';

-- Reconcile paid kits created before this flow. Insufficient stock aborts the
-- migration instead of leaving only part of an order reserved.
do $$
declare
  v_pedido record;
begin
  for v_pedido in
    select raiz.id
      from public.pedidos raiz
     where raiz.plano_id is null
       and raiz.pagamento_status = 'approved'
       and exists (
         select 1
           from public.pedidos entrega
          where entrega.pedido_origem_id = raiz.id
            and entrega.plano_id is not null
            and entrega.status <> 'Cancelado'
            and not entrega.plano_estoque_baixado
       )
     order by raiz.id
  loop
    perform public.reservar_estoque_kit_pedido(v_pedido.id);
  end loop;
end;
$$;
