alter table public.creditos_pagamento
  add column if not exists valor_reservado numeric(12, 2) not null default 0;

update public.creditos_pagamento
set chave = upper(btrim(chave)),
    valor_origem = round(valor_origem, 2),
    valor_disponivel = round(valor_disponivel, 2),
    valor_reservado = greatest(round(valor_reservado, 2), 0),
    ativo = coalesce(ativo, true);

alter table public.creditos_pagamento
  alter column ativo set not null;

alter table public.creditos_pagamento
  drop constraint if exists creditos_pagamento_valor_origem_check,
  drop constraint if exists creditos_pagamento_valor_disponivel_check,
  drop constraint if exists creditos_pagamento_valor_reservado_check,
  drop constraint if exists creditos_pagamento_tipo_check;

alter table public.creditos_pagamento
  add constraint creditos_pagamento_valor_origem_check check (valor_origem > 0),
  add constraint creditos_pagamento_valor_disponivel_check check (valor_disponivel >= 0),
  add constraint creditos_pagamento_valor_reservado_check check (valor_reservado >= 0 and valor_reservado <= valor_disponivel),
  add constraint creditos_pagamento_tipo_check check (tipo in ('Devolução', 'Bonificação', 'Premiação', 'Venda Externa'));

create unique index if not exists creditos_pagamento_chave_normalizada_uidx
  on public.creditos_pagamento (upper(btrim(chave)));

alter table public.pedidos
  add column if not exists credito_pagamento_id integer references public.creditos_pagamento(id),
  add column if not exists credito_valor_aplicado numeric(12, 2) not null default 0,
  add column if not exists credito_valor_original numeric(12, 2),
  add column if not exists credito_status text;

alter table public.pedidos
  drop constraint if exists pedidos_credito_valor_aplicado_check,
  drop constraint if exists pedidos_credito_status_check;

alter table public.pedidos
  add constraint pedidos_credito_valor_aplicado_check check (credito_valor_aplicado >= 0),
  add constraint pedidos_credito_status_check check (credito_status is null or credito_status in ('reservado', 'consumido', 'liberado'));

create table if not exists public.creditos_pagamento_movimentos (
  id bigint generated by default as identity primary key,
  credito_id integer not null references public.creditos_pagamento(id),
  pedido_id bigint not null references public.pedidos(id),
  valor numeric(12, 2) not null check (valor > 0),
  status text not null check (status in ('reservado', 'consumido', 'liberado')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  expira_em timestamptz,
  unique (pedido_id)
);

create index if not exists creditos_pagamento_movimentos_credito_status_idx
  on public.creditos_pagamento_movimentos (credito_id, status);

alter table public.creditos_pagamento enable row level security;
alter table public.creditos_pagamento_movimentos enable row level security;

drop policy if exists "Admins gerenciam creditos de pagamento" on public.creditos_pagamento;
create policy "Admins gerenciam creditos de pagamento"
  on public.creditos_pagamento for all to authenticated
  using (public.is_viva_leve_admin())
  with check (public.is_viva_leve_admin());

drop policy if exists "Admins leem movimentos de creditos" on public.creditos_pagamento_movimentos;
create policy "Admins leem movimentos de creditos"
  on public.creditos_pagamento_movimentos for select to authenticated
  using (public.is_viva_leve_admin());

create or replace function public.normalizar_credito_pagamento()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.chave := upper(btrim(new.chave));
  new.email_restricao := nullif(lower(btrim(new.email_restricao)), '');
  new.valor_origem := round(new.valor_origem, 2);
  if tg_op = 'INSERT' then
    new.valor_disponivel := new.valor_origem;
    new.valor_reservado := 0;
  end if;
  new.atualizado_em := current_timestamp;
  return new;
end;
$$;

drop trigger if exists creditos_pagamento_normalizar_trigger on public.creditos_pagamento;
create trigger creditos_pagamento_normalizar_trigger
before insert or update on public.creditos_pagamento
for each row execute function public.normalizar_credito_pagamento();

create or replace function public.aplicar_credito_pedido(
  p_pedido_id text,
  p_chave text,
  p_cliente_id uuid,
  p_cliente_email text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos%rowtype;
  v_credito public.creditos_pagamento%rowtype;
  v_movimento public.creditos_pagamento_movimentos%rowtype;
  v_disponivel numeric(12, 2);
  v_aplicado numeric(12, 2);
  v_restante numeric(12, 2);
  v_item jsonb;
  v_produto_id integer;
  v_quantidade integer;
begin
  select * into v_pedido
  from public.pedidos
  where id::text = p_pedido_id
  for update;

  if not found or v_pedido.cliente_id is distinct from p_cliente_id then
    raise exception 'Pedido não encontrado para este usuário.';
  end if;
  if v_pedido.pagamento_status = 'approved' then
    raise exception 'Este pedido já foi pago.';
  end if;
  if v_pedido.credito_pagamento_id is not null and v_pedido.credito_status in ('reservado', 'consumido') then
    raise exception 'Este pedido já possui uma chave de crédito aplicada.';
  end if;
  if round(v_pedido.valor_total, 2) <= 0 then
    raise exception 'O pedido não possui valor para abatimento.';
  end if;

  select * into v_credito
  from public.creditos_pagamento
  where upper(btrim(chave)) = upper(btrim(p_chave))
  for update;

  if not found then
    raise exception 'Chave de crédito não encontrada.';
  end if;

  for v_movimento in
    select *
    from public.creditos_pagamento_movimentos
    where credito_id = v_credito.id
      and status = 'reservado'
      and expira_em <= now()
    for update
  loop
    update public.pedidos
       set valor_total = coalesce(credito_valor_original, valor_total),
           credito_status = 'liberado',
           credito_pagamento_id = null,
           credito_valor_aplicado = 0,
           credito_valor_original = null,
           updated_at = timezone('utc'::text, now())
     where id = v_movimento.pedido_id
       and credito_status = 'reservado';

    update public.creditos_pagamento_movimentos
       set status = 'liberado', atualizado_em = now()
     where id = v_movimento.id;

    v_credito.valor_reservado := greatest(v_credito.valor_reservado - v_movimento.valor, 0);
  end loop;

  update public.creditos_pagamento
     set valor_reservado = v_credito.valor_reservado
   where id = v_credito.id;

  if not v_credito.ativo then
    raise exception 'Esta chave de crédito está inativa.';
  end if;
  if v_credito.email_restricao is not null
     and lower(btrim(v_credito.email_restricao)) <> lower(btrim(coalesce(p_cliente_email, ''))) then
    raise exception 'Esta chave de crédito pertence a outro usuário.';
  end if;

  v_disponivel := greatest(round(v_credito.valor_disponivel - v_credito.valor_reservado, 2), 0);
  if v_disponivel <= 0 then
    raise exception 'Esta chave de crédito não possui saldo disponível.';
  end if;

  v_aplicado := least(v_disponivel, round(v_pedido.valor_total, 2));
  v_restante := round(v_pedido.valor_total - v_aplicado, 2);

  if v_restante <= 0 then
    for v_item in
      select value from jsonb_array_elements(coalesce(v_pedido.itens::jsonb, '[]'::jsonb))
    loop
      v_produto_id := nullif(v_item ->> 'id', '')::integer;
      v_quantidade := greatest(coalesce(nullif(v_item ->> 'quantidade', '')::integer, 0), 0);
      if v_produto_id is not null and v_quantidade > 0 then
        update public.produtos
           set estoque = estoque - v_quantidade
         where id = v_produto_id and estoque >= v_quantidade;
        if not found then
          raise exception 'Estoque insuficiente para o produto %.', v_produto_id;
        end if;
      end if;
    end loop;

    update public.creditos_pagamento
       set valor_disponivel = round(valor_disponivel - v_aplicado, 2),
           ativo = case when round(valor_disponivel - v_aplicado, 2) <= 0 then false else ativo end,
           atualizado_em = current_timestamp
     where id = v_credito.id;

    update public.pedidos
       set credito_pagamento_id = v_credito.id,
           credito_valor_aplicado = v_aplicado,
           credito_valor_original = v_pedido.valor_total,
           credito_status = 'consumido',
           valor_total = 0,
           meio_pagamento = 'credito',
           pagamento_status = 'approved',
           status = 'Em Preparo',
           updated_at = timezone('utc'::text, now())
     where id = v_pedido.id;

    insert into public.creditos_pagamento_movimentos (credito_id, pedido_id, valor, status)
    values (v_credito.id, v_pedido.id, v_aplicado, 'consumido');
  else
    update public.creditos_pagamento
       set valor_reservado = round(valor_reservado + v_aplicado, 2),
           atualizado_em = current_timestamp
     where id = v_credito.id;

    update public.pedidos
       set credito_pagamento_id = v_credito.id,
           credito_valor_aplicado = v_aplicado,
           credito_valor_original = v_pedido.valor_total,
           credito_status = 'reservado',
           valor_total = v_restante,
           updated_at = timezone('utc'::text, now())
     where id = v_pedido.id;

    insert into public.creditos_pagamento_movimentos (credito_id, pedido_id, valor, status, expira_em)
    values (v_credito.id, v_pedido.id, v_aplicado, 'reservado', now() + interval '24 hours');
  end if;

  return jsonb_build_object(
    'credito_id', v_credito.id,
    'valor_aplicado', v_aplicado,
    'valor_restante', greatest(v_restante, 0),
    'quitado', v_restante <= 0
  );
end;
$$;

create or replace function public.finalizar_credito_pedido(p_pedido_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos%rowtype;
  v_movimento public.creditos_pagamento_movimentos%rowtype;
begin
  select * into v_pedido from public.pedidos where id::text = p_pedido_id for update;
  if not found or v_pedido.credito_status <> 'reservado' then return; end if;

  select * into v_movimento
  from public.creditos_pagamento_movimentos
  where pedido_id = v_pedido.id and status = 'reservado'
  for update;
  if not found then return; end if;

  update public.creditos_pagamento
     set valor_disponivel = round(valor_disponivel - v_movimento.valor, 2),
         valor_reservado = greatest(round(valor_reservado - v_movimento.valor, 2), 0),
         ativo = case when round(valor_disponivel - v_movimento.valor, 2) <= 0 then false else ativo end,
         atualizado_em = current_timestamp
   where id = v_movimento.credito_id
     and valor_disponivel >= v_movimento.valor
     and valor_reservado >= v_movimento.valor;
  if not found then raise exception 'Saldo reservado da chave de crédito está inconsistente.'; end if;

  update public.creditos_pagamento_movimentos
     set status = 'consumido', atualizado_em = now(), expira_em = null
   where id = v_movimento.id;
  update public.pedidos
     set credito_status = 'consumido', updated_at = timezone('utc'::text, now())
   where id = v_pedido.id;
end;
$$;

create or replace function public.liberar_credito_pedido(p_pedido_id text, p_cliente_id uuid default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.pedidos%rowtype;
  v_movimento public.creditos_pagamento_movimentos%rowtype;
begin
  select * into v_pedido from public.pedidos where id::text = p_pedido_id for update;
  if not found then raise exception 'Pedido não encontrado.'; end if;
  if p_cliente_id is not null and v_pedido.cliente_id is distinct from p_cliente_id then
    raise exception 'Pedido não encontrado para este usuário.';
  end if;
  if v_pedido.credito_status <> 'reservado' then return; end if;

  select * into v_movimento
  from public.creditos_pagamento_movimentos
  where pedido_id = v_pedido.id and status = 'reservado'
  for update;
  if not found then return; end if;

  update public.creditos_pagamento
     set valor_reservado = greatest(round(valor_reservado - v_movimento.valor, 2), 0),
         atualizado_em = current_timestamp
   where id = v_movimento.credito_id;
  update public.creditos_pagamento_movimentos
     set status = 'liberado', atualizado_em = now(), expira_em = null
   where id = v_movimento.id;
  update public.pedidos
     set valor_total = coalesce(credito_valor_original, valor_total),
         credito_status = 'liberado',
         credito_pagamento_id = null,
         credito_valor_aplicado = 0,
         credito_valor_original = null,
         updated_at = timezone('utc'::text, now())
   where id = v_pedido.id;
end;
$$;

revoke all on function public.aplicar_credito_pedido(text, text, uuid, text) from public, anon, authenticated;
revoke all on function public.finalizar_credito_pedido(text) from public, anon, authenticated;
revoke all on function public.liberar_credito_pedido(text, uuid) from public, anon, authenticated;
grant execute on function public.aplicar_credito_pedido(text, text, uuid, text) to service_role;
grant execute on function public.finalizar_credito_pedido(text) to service_role;
grant execute on function public.liberar_credito_pedido(text, uuid) to service_role;
