create table if not exists public.loja_acessos (
  id bigint generated by default as identity primary key,
  sessao_id uuid not null unique,
  acessado_em timestamptz not null default now()
);

comment on table public.loja_acessos is
  'Contagem anônima e minimizada de sessões que abriram a loja.';

create index if not exists loja_acessos_acessado_em_idx
  on public.loja_acessos (acessado_em desc);

alter table public.loja_acessos enable row level security;

revoke all on table public.loja_acessos from anon, authenticated;
revoke all on sequence public.loja_acessos_id_seq from anon, authenticated;
