-- Perfil de entregador e fluxo logístico seguro sobre a tabela pedidos existente.

alter table public.admin_usuario_roles
  drop constraint if exists admin_usuario_roles_role_check;
alter table public.admin_usuario_roles
  add constraint admin_usuario_roles_role_check
  check (role in ('admin', 'trainer', 'delivery'));

alter table public.admin_usuario_roles
  add column if not exists user_id uuid references auth.users(id) on delete set null,
  add column if not exists telefone text,
  add column if not exists observacoes text;

update public.admin_usuario_roles roles
set user_id = users.id
from auth.users users
where roles.user_id is null
  and lower(users.email) = lower(roles.email);

create unique index if not exists admin_usuario_roles_user_role_uidx
  on public.admin_usuario_roles (user_id, role)
  where user_id is not null;

create or replace function public.is_viva_leve_delivery()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.has_viva_leve_role('delivery');
$$;

alter table public.pedidos
  add column if not exists entregador_id uuid references auth.users(id) on delete set null,
  add column if not exists entrega_atribuida_em timestamptz,
  add column if not exists saiu_entrega_em timestamptz,
  add column if not exists entregue_em timestamptz,
  add column if not exists entrega_metodo_confirmacao text,
  add column if not exists entrega_confirmada_por uuid references auth.users(id) on delete set null,
  add column if not exists entrega_observacoes text,
  add column if not exists entrega_janela text,
  add column if not exists entrega_codigo_salt uuid,
  add column if not exists entrega_codigo_hash bytea,
  add column if not exists entrega_codigo_gerado_em timestamptz,
  add column if not exists entrega_codigo_utilizado_em timestamptz,
  add column if not exists entrega_tentativas_codigo integer not null default 0,
  add column if not exists entrega_bloqueado_ate timestamptz;

alter table public.pedidos
  drop constraint if exists pedidos_entrega_metodo_confirmacao_check;
alter table public.pedidos
  add constraint pedidos_entrega_metodo_confirmacao_check
  check (
    entrega_metodo_confirmacao is null
    or entrega_metodo_confirmacao in ('codigo_entregador', 'cliente', 'administrador')
  );

create index if not exists pedidos_entregador_status_idx
  on public.pedidos (entregador_id, status, criado_em desc)
  where entregador_id is not null;
create index if not exists pedidos_entregue_em_idx
  on public.pedidos (entregue_em desc)
  where entregue_em is not null;

create table if not exists public.entregas_historico (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references public.pedidos(id) on delete restrict,
  evento text not null check (evento in (
    'atribuido', 'reatribuido', 'atribuicao_removida', 'saiu_para_entrega',
    'entregue', 'status_alterado', 'tentativa_codigo_invalido'
  )),
  status_anterior text,
  status_novo text,
  entregador_anterior_id uuid references auth.users(id) on delete set null,
  entregador_novo_id uuid references auth.users(id) on delete set null,
  ator_id uuid references auth.users(id) on delete set null,
  ator_tipo text not null check (ator_tipo in ('admin', 'delivery', 'client', 'system')),
  metodo_confirmacao text,
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

create index if not exists entregas_historico_pedido_idx
  on public.entregas_historico (pedido_id, criado_em desc);
create index if not exists entregas_historico_entregador_idx
  on public.entregas_historico (entregador_novo_id, criado_em desc)
  where entregador_novo_id is not null;
create index if not exists entregas_historico_entregador_anterior_idx
  on public.entregas_historico (entregador_anterior_id)
  where entregador_anterior_id is not null;
create index if not exists entregas_historico_ator_idx
  on public.entregas_historico (ator_id)
  where ator_id is not null;
create index if not exists pedidos_entrega_confirmada_por_idx
  on public.pedidos (entrega_confirmada_por)
  where entrega_confirmada_por is not null;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.entrega_segredo (
  id boolean primary key default true check (id = true),
  segredo bytea not null,
  criado_em timestamptz not null default now()
);

insert into private.entrega_segredo (id, segredo)
values (true, extensions.gen_random_bytes(32))
on conflict (id) do nothing;

revoke all on private.entrega_segredo from public, anon, authenticated;

create or replace function private.codigo_entrega(p_pedido_id bigint, p_salt uuid)
returns text
language plpgsql
stable
security definer
set search_path = private, extensions, pg_temp
as $$
declare
  v_segredo bytea;
  v_numero bigint;
begin
  select segredo into v_segredo from private.entrega_segredo where id = true;
  v_numero := (('x' || substr(encode(extensions.hmac(
    convert_to(p_pedido_id::text || ':' || p_salt::text, 'utf8'),
    v_segredo,
    'sha256'
  ), 'hex'), 1, 8))::bit(32)::bigint % 1000000);
  return lpad(v_numero::text, 6, '0');
end;
$$;

create or replace function private.hash_codigo_entrega(p_codigo text, p_salt uuid)
returns bytea
language plpgsql
stable
security definer
set search_path = private, extensions, pg_temp
as $$
declare
  v_segredo bytea;
begin
  select segredo into v_segredo from private.entrega_segredo where id = true;
  return extensions.hmac(
    convert_to(trim(p_codigo) || ':' || p_salt::text, 'utf8'),
    v_segredo,
    'sha256'
  );
end;
$$;

revoke all on function private.codigo_entrega(bigint, uuid) from public, anon, authenticated;
revoke all on function private.hash_codigo_entrega(text, uuid) from public, anon, authenticated;

create or replace function public.entrega_ator_tipo()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case
    when auth.uid() is null then 'system'
    when public.is_viva_leve_admin() then 'admin'
    when public.is_viva_leve_delivery() then 'delivery'
    else 'client'
  end;
$$;

create or replace function public.preparar_codigo_status_entrega()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_codigo text;
begin
  if new.status = 'Saiu para Entrega' and old.status is distinct from 'Saiu para Entrega' then
    if new.entregador_id is null then
      raise exception 'Atribua um entregador antes de iniciar a entrega.' using errcode = '23514';
    end if;
    new.entrega_codigo_salt := gen_random_uuid();
    v_codigo := private.codigo_entrega(new.id, new.entrega_codigo_salt);
    new.entrega_codigo_hash := private.hash_codigo_entrega(v_codigo, new.entrega_codigo_salt);
    new.entrega_codigo_gerado_em := now();
    new.entrega_codigo_utilizado_em := null;
    new.entrega_tentativas_codigo := 0;
    new.entrega_bloqueado_ate := null;
    new.saiu_entrega_em := coalesce(new.saiu_entrega_em, now());
  elsif new.status = 'Entregue' and old.status is distinct from 'Entregue' then
    new.entregue_em := coalesce(new.entregue_em, now());
    new.entrega_codigo_utilizado_em := coalesce(new.entrega_codigo_utilizado_em, now());
    new.entrega_codigo_hash := null;
    new.entrega_codigo_salt := null;
    new.entrega_bloqueado_ate := null;
  elsif old.status = 'Saiu para Entrega' and new.status not in ('Saiu para Entrega', 'Entregue') then
    new.entrega_codigo_hash := null;
    new.entrega_codigo_salt := null;
    new.entrega_codigo_utilizado_em := now();
    new.entrega_bloqueado_ate := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pedidos_preparar_codigo_entrega on public.pedidos;
create trigger trg_pedidos_preparar_codigo_entrega
before update of status on public.pedidos
for each row execute function public.preparar_codigo_status_entrega();

create or replace function public.auditar_pedido_entrega()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_evento text;
  v_ator_tipo text;
begin
  if old.entregador_id is distinct from new.entregador_id then
    v_evento := case
      when old.entregador_id is null then 'atribuido'
      when new.entregador_id is null then 'atribuicao_removida'
      else 'reatribuido'
    end;
    v_ator_tipo := case
      when new.status = 'Entregue' and new.entrega_metodo_confirmacao = 'cliente' then 'client'
      when new.status = 'Entregue' and new.entrega_metodo_confirmacao = 'codigo_entregador' then 'delivery'
      else public.entrega_ator_tipo()
    end;

    insert into public.entregas_historico (
      pedido_id, evento, status_anterior, status_novo, entregador_anterior_id,
      entregador_novo_id, ator_id, ator_tipo
    ) values (
      new.id, v_evento, old.status, new.status, old.entregador_id,
      new.entregador_id, auth.uid(), public.entrega_ator_tipo()
    );
  end if;

  if old.status is distinct from new.status then
    v_evento := case
      when new.status = 'Saiu para Entrega' then 'saiu_para_entrega'
      when new.status = 'Entregue' then 'entregue'
      else 'status_alterado'
    end;
    insert into public.entregas_historico (
      pedido_id, evento, status_anterior, status_novo, entregador_anterior_id,
      entregador_novo_id, ator_id, ator_tipo, metodo_confirmacao
    ) values (
      new.id, v_evento, old.status, new.status, old.entregador_id,
      new.entregador_id, auth.uid(), v_ator_tipo, new.entrega_metodo_confirmacao
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pedidos_auditar_entrega on public.pedidos;
create trigger trg_pedidos_auditar_entrega
after update of status, entregador_id on public.pedidos
for each row execute function public.auditar_pedido_entrega();

create or replace function public.atribuir_entregador_pedido(
  p_pedido_id bigint,
  p_entregador_id uuid,
  p_observacoes text default null,
  p_janela text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_pedido public.pedidos%rowtype;
begin
  if not public.is_viva_leve_admin() then
    raise exception 'Acesso restrito a administradores.' using errcode = '42501';
  end if;

  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found then raise exception 'Pedido não encontrado.' using errcode = 'P0002'; end if;
  if v_pedido.status = 'Entregue' then raise exception 'Pedido já entregue não pode ser reatribuído.'; end if;

  if p_entregador_id is not null and not exists (
    select 1
    from auth.users users
    join public.admin_usuario_roles roles on lower(roles.email) = lower(users.email)
    where users.id = p_entregador_id and roles.role = 'delivery' and roles.ativo = true
  ) then
    raise exception 'Entregador ativo não encontrado.' using errcode = 'P0002';
  end if;

  update public.pedidos
  set entregador_id = p_entregador_id,
      entrega_atribuida_em = case when p_entregador_id is null then null else now() end,
      entrega_observacoes = nullif(trim(p_observacoes), ''),
      entrega_janela = nullif(trim(p_janela), ''),
      status = case
        when p_entregador_id is null and status = 'Saiu para Entrega' then 'Em Preparo'
        else status
      end,
      updated_at = now()
  where id = p_pedido_id;
end;
$$;

create or replace function public.iniciar_entrega_pedido(p_pedido_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_pedido public.pedidos%rowtype;
begin
  if not public.is_viva_leve_delivery() then
    raise exception 'Acesso restrito a entregadores.' using errcode = '42501';
  end if;
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found or v_pedido.entregador_id is distinct from auth.uid() then
    raise exception 'Entrega não encontrada ou não atribuída a você.' using errcode = '42501';
  end if;
  if v_pedido.status not in ('Recebido', 'Em Preparo') then
    raise exception 'A entrega só pode ser iniciada após o pedido estar recebido ou em preparo.';
  end if;

  update public.pedidos
  set status = 'Saiu para Entrega', updated_at = now()
  where id = p_pedido_id and entregador_id = auth.uid();
end;
$$;

create or replace function public.confirmar_entrega_por_codigo(p_pedido_id bigint, p_codigo text)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_pedido public.pedidos%rowtype;
  v_hash bytea;
  v_tentativas integer;
begin
  if not public.is_viva_leve_delivery() then
    raise exception 'Acesso restrito a entregadores.' using errcode = '42501';
  end if;

  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found or v_pedido.entregador_id is distinct from auth.uid() then
    raise exception 'Entrega não encontrada ou não atribuída a você.' using errcode = '42501';
  end if;
  if v_pedido.status = 'Entregue' or v_pedido.entrega_codigo_utilizado_em is not null then
    return jsonb_build_object('ok', false, 'message', 'Esta entrega já foi confirmada.');
  end if;
  if v_pedido.status <> 'Saiu para Entrega' or v_pedido.entrega_codigo_hash is null then
    return jsonb_build_object('ok', false, 'message', 'A entrega ainda não está em rota.');
  end if;
  if v_pedido.entrega_bloqueado_ate is not null and v_pedido.entrega_bloqueado_ate > now() then
    return jsonb_build_object('ok', false, 'message', 'Muitas tentativas. Aguarde 15 minutos e tente novamente.');
  end if;

  v_tentativas := case
    when v_pedido.entrega_bloqueado_ate is not null and v_pedido.entrega_bloqueado_ate <= now() then 0
    else v_pedido.entrega_tentativas_codigo
  end;
  v_hash := private.hash_codigo_entrega(trim(coalesce(p_codigo, '')), v_pedido.entrega_codigo_salt);

  if v_hash <> v_pedido.entrega_codigo_hash then
    v_tentativas := v_tentativas + 1;
    update public.pedidos
    set entrega_tentativas_codigo = v_tentativas,
        entrega_bloqueado_ate = case when v_tentativas >= 5 then now() + interval '15 minutes' else null end,
        updated_at = now()
    where id = p_pedido_id;
    insert into public.entregas_historico (
      pedido_id, evento, status_anterior, status_novo, entregador_anterior_id,
      entregador_novo_id, ator_id, ator_tipo, detalhes
    ) values (
      p_pedido_id, 'tentativa_codigo_invalido', v_pedido.status, v_pedido.status,
      v_pedido.entregador_id, v_pedido.entregador_id, auth.uid(), 'delivery',
      jsonb_build_object('tentativa', v_tentativas, 'bloqueado', v_tentativas >= 5)
    );
    return jsonb_build_object(
      'ok', false,
      'message', case when v_tentativas >= 5
        then 'Código inválido. Novas tentativas foram bloqueadas por 15 minutos.'
        else 'Código de confirmação inválido.' end
    );
  end if;

  update public.pedidos
  set status = 'Entregue',
      entregue_em = now(),
      entrega_metodo_confirmacao = 'codigo_entregador',
      entrega_confirmada_por = auth.uid(),
      entrega_codigo_utilizado_em = now(),
      updated_at = now()
  where id = p_pedido_id and status = 'Saiu para Entrega';

  return jsonb_build_object('ok', true, 'message', 'Entrega confirmada com sucesso.');
end;
$$;

create or replace function public.confirmar_entrega_pelo_cliente(p_pedido_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_pedido public.pedidos%rowtype;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id for update;
  if not found or v_pedido.cliente_id is distinct from auth.uid() then
    raise exception 'Pedido não encontrado.' using errcode = '42501';
  end if;
  if v_pedido.status = 'Entregue' then
    return jsonb_build_object('ok', false, 'message', 'Este pedido já foi confirmado como entregue.');
  end if;
  if v_pedido.status <> 'Saiu para Entrega' then
    return jsonb_build_object('ok', false, 'message', 'O pedido ainda não saiu para entrega.');
  end if;

  update public.pedidos
  set status = 'Entregue',
      entregue_em = now(),
      entrega_metodo_confirmacao = 'cliente',
      entrega_confirmada_por = auth.uid(),
      entrega_codigo_utilizado_em = now(),
      updated_at = now()
  where id = p_pedido_id and status = 'Saiu para Entrega';

  return jsonb_build_object('ok', true, 'message', 'Recebimento confirmado. Obrigado!');
end;
$$;

create or replace function public.obter_codigo_entrega_cliente(p_pedido_id bigint)
returns text
language plpgsql
stable
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_pedido public.pedidos%rowtype;
begin
  select * into v_pedido from public.pedidos where id = p_pedido_id;
  if not found or v_pedido.cliente_id is distinct from auth.uid() then
    raise exception 'Pedido não encontrado.' using errcode = '42501';
  end if;
  if v_pedido.status <> 'Saiu para Entrega'
     or v_pedido.entrega_codigo_salt is null
     or v_pedido.entrega_codigo_utilizado_em is not null then
    return null;
  end if;
  return private.codigo_entrega(v_pedido.id, v_pedido.entrega_codigo_salt);
end;
$$;

create or replace function public.listar_minhas_entregas()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(jsonb_agg(to_jsonb(lista) order by lista.ordem_status, lista.criado_em), '[]'::jsonb)
  from (
    select
      pedidos.id,
      pedidos.status,
      pedidos.endereco_entrega,
      pedidos.endereco,
      pedidos.itens,
      pedidos.criado_em,
      pedidos.updated_at,
      pedidos.entrega_atribuida_em,
      pedidos.saiu_entrega_em,
      pedidos.entregue_em,
      pedidos.entrega_observacoes,
      pedidos.entrega_janela,
      pedidos.meio_pagamento,
      pedidos.pagamento_status,
      pedidos.tipo_venda,
      coalesce(pedidos.cliente_nome_balcao, clientes.nome_completo, perfis.nome, 'Cliente') as cliente_nome,
      coalesce(pedidos.cliente_telefone_balcao, clientes.telefone, perfis.telefone, '') as cliente_telefone,
      clientes.endereco_complemento,
      null::text as endereco_referencia,
      case
        when pedidos.status = 'Saiu para Entrega' then 1
        when pedidos.status = 'Entregue' then 3
        else 2
      end as ordem_status
    from public.pedidos pedidos
    left join public.perfis_clientes clientes on clientes.id = pedidos.cliente_id
    left join public.perfis perfis on perfis.id = pedidos.cliente_id
    where public.is_viva_leve_delivery()
      and pedidos.entregador_id = auth.uid()
      and (
        pedidos.status <> 'Entregue'
        or coalesce(pedidos.entregue_em, pedidos.updated_at) >= date_trunc('day', now())
      )
  ) lista;
$$;

create or replace function public.pode_ver_historico_entrega(p_pedido_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_viva_leve_admin() or exists (
    select 1 from public.pedidos pedidos
    where pedidos.id = p_pedido_id
      and (pedidos.cliente_id = auth.uid() or pedidos.entregador_id = auth.uid())
  );
$$;

alter table public.entregas_historico enable row level security;
drop policy if exists entregas_historico_leitura_autorizada on public.entregas_historico;
create policy entregas_historico_leitura_autorizada
  on public.entregas_historico for select to authenticated
  using (public.pode_ver_historico_entrega(pedido_id));

revoke all on public.entregas_historico from anon;
grant select on public.entregas_historico to authenticated;

revoke all on function public.is_viva_leve_delivery() from public, anon;
revoke all on function public.entrega_ator_tipo() from public, anon, authenticated;
revoke all on function public.preparar_codigo_status_entrega() from public, anon, authenticated;
revoke all on function public.auditar_pedido_entrega() from public, anon, authenticated;
revoke all on function public.pode_ver_historico_entrega(bigint) from public, anon, authenticated;
revoke all on function public.atribuir_entregador_pedido(bigint, uuid, text, text) from public, anon;
revoke all on function public.iniciar_entrega_pedido(bigint) from public, anon;
revoke all on function public.confirmar_entrega_por_codigo(bigint, text) from public, anon;
revoke all on function public.confirmar_entrega_pelo_cliente(bigint) from public, anon;
revoke all on function public.obter_codigo_entrega_cliente(bigint) from public, anon;
revoke all on function public.listar_minhas_entregas() from public, anon;

grant execute on function public.is_viva_leve_delivery() to authenticated;
grant execute on function public.atribuir_entregador_pedido(bigint, uuid, text, text) to authenticated;
grant execute on function public.iniciar_entrega_pedido(bigint) to authenticated;
grant execute on function public.confirmar_entrega_por_codigo(bigint, text) to authenticated;
grant execute on function public.confirmar_entrega_pelo_cliente(bigint) to authenticated;
grant execute on function public.obter_codigo_entrega_cliente(bigint) to authenticated;
grant execute on function public.listar_minhas_entregas() to authenticated;
grant execute on function public.pode_ver_historico_entrega(bigint) to authenticated;

comment on column public.pedidos.entregador_id is 'Responsável atual pela entrega; não cria pedido paralelo.';
comment on column public.pedidos.entrega_codigo_hash is 'HMAC do código de uso único; o código em texto não é persistido.';
comment on table public.entregas_historico is 'Auditoria imutável de atribuições, rota, tentativas e confirmação da entrega.';
